# Generated by Django 5.1.3 on 2024-11-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
    ]
