# Generated by Django 5.1.3 on 2024-11-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
